# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('access_token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('email', models.EmailField(default=b'', max_length=200)),
                ('password', models.CharField(default=b'', max_length=200)),
                ('salt', models.CharField(default=b'', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.User'),
        ),
    ]
